name: Formatting CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dprint/check@v2.0
